title: "내 한국어 사이트"
default_lang: ko
permalink: /ko/:year/:categories/:title/  # year를 categories 앞에 위치시킴

search                   : true
search_full_content      : true
search_provider          : lunr

collections:
  posts:
    output: true
    path: "_posts/ko/:year/:categories"  # 파일 경로는 연도와 카테고리를 포함
    permalink: /ko/:year/:categories/:title/  # 동일하게 permalink 설정